//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabynetPro.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileInformation
    {
        public long Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserCreated { get; set; }
        public string FileNameSource { get; set; }
        public string FileNameSystem { get; set; }
        public string FileNameDescription { get; set; }
        public string FileTag { get; set; }
        public string FileType { get; set; }
        public long FileSize { get; set; }
        public int CategoryId { get; set; }
        public long FolderId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
