//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabynetPro.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAuditLog
    {
        public long Id { get; set; }
        public long FileInformationId { get; set; }
        public System.DateTime AuditPeriod { get; set; }
        public int AuditType { get; set; }
        public int AuditCommitUserId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
